---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-sleep
  annotations:
    kapp.k14s.io/disable-wait: ""
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000); sleep(30)"]
  backoffLimit: 4
